"""Enum definitions generated from ``resources/openapi.json``.

Do not edit by hand: run ``python3 scripts/generate_enums.py`` after
updating the spec.
"""

from __future__ import annotations

from .helpers import EnumSpec

ALARM_STATUS = EnumSpec(
    prefix="ALARM_STATUS_",
    values=(
        "ALARM_STATUS_UNSPECIFIED",
        "ALARM_STATUS_IDLE",
        "ALARM_STATUS_TRIGGERED",
    ),
)

AVAILABILITY_STATUS = EnumSpec(
    prefix="AVAILABILITY_STATUS_",
    values=(
        "AVAILABILITY_STATUS_UNSPECIFIED",
        "AVAILABILITY_STATUS_AVAILABLE",
        "AVAILABILITY_STATUS_UNAVAILABLE",
    ),
)

AVAILABLE_OPTIMIZED_CHARGING = EnumSpec(
    prefix="",
    values=(
        "UNAVAILABLE",
        "INTELLIGENT_TIMER",
        "PRICED_OPTIMIZED_CHARGING",
    ),
)

BATTERY_PRECONDITIONING = EnumSpec(
    prefix="BP_",
    values=(
        "BP_UNDEFINED",
        "BP_OFF",
        "BP_WHEN_PLUGGED",
        "BP_ON",
    ),
)

BRAKE_FLUID_LEVEL_WARNING = EnumSpec(
    prefix="BRAKE_FLUID_LEVEL_WARNING_",
    values=(
        "BRAKE_FLUID_LEVEL_WARNING_UNSPECIFIED",
        "BRAKE_FLUID_LEVEL_WARNING_NO_WARNING",
        "BRAKE_FLUID_LEVEL_WARNING_TOO_LOW",
        "BRAKE_FLUID_LEVEL_WARNING_CRITICALLY_LOW",
    ),
)

CHARGER_CONNECTION_STATUS = EnumSpec(
    prefix="CHARGER_CONNECTION_STATUS_",
    values=(
        "CHARGER_CONNECTION_STATUS_UNSPECIFIED",
        "CHARGER_CONNECTION_STATUS_CONNECTED",
        "CHARGER_CONNECTION_STATUS_DISCONNECTED",
        "CHARGER_CONNECTION_STATUS_FAULT",
    ),
)

CHARGER_POWER_STATUS = EnumSpec(
    prefix="CHARGER_POWER_STATUS_",
    values=(
        "CHARGER_POWER_STATUS_UNSPECIFIED",
        "CHARGER_POWER_STATUS_NO_POWER_AVAILABLE",
        "CHARGER_POWER_STATUS_INITIALIZATION",
        "CHARGER_POWER_STATUS_POWER_AVAILABLE_BUT_NOT_ACTIVATED",
        "CHARGER_POWER_STATUS_PROVIDING_POWER",
        "CHARGER_POWER_STATUS_FAULT",
    ),
)

CHARGE_TARGET_LEVEL_SETTING_TYPE = EnumSpec(
    prefix="",
    values=(
        "CHARGE_TARGET_LEVEL_SETTING_TYPE_UNSPECIFIED",
        "DAILY",
        "LONG_TRIP",
        "CUSTOM",
    ),
)

CHARGING_STATUS = EnumSpec(
    prefix="CHARGING_STATUS_",
    values=(
        "CHARGING_STATUS_UNSPECIFIED",
        "CHARGING_STATUS_CHARGING",
        "CHARGING_STATUS_IDLE",
        "CHARGING_STATUS_SCHEDULED",
        "CHARGING_STATUS_DISCHARGING",
        "CHARGING_STATUS_ERROR",
        "CHARGING_STATUS_SMART_CHARGING",
        "CHARGING_STATUS_SMART_CHARGING_PAUSED",
        "CHARGING_STATUS_DONE",
    ),
)

CHARGING_STATUS_V2 = EnumSpec(
    prefix="CHARGING_STATUS_V2_",
    values=(
        "CHARGING_STATUS_V2_UNSPECIFIED",
        "CHARGING_STATUS_V2_CHARGING",
        "CHARGING_STATUS_V2_CHARGE_LEVEL_IS_GOOD_TO_GO",
        "CHARGING_STATUS_V2_CHARGING_IS_EN_ROUTE",
        "CHARGING_STATUS_V2_CHARGING_TOWARDS_MIN_SOC",
        "CHARGING_STATUS_V2_IDLE",
        "CHARGING_STATUS_V2_SCHEDULED",
        "CHARGING_STATUS_V2_SCHEDULED_CHARGING_CANNOT_COMPLETE",
        "CHARGING_STATUS_V2_SCHEDULED_CHARGING_WILL_COMPLETE",
        "CHARGING_STATUS_V2_DISCHARGING",
        "CHARGING_STATUS_V2_DISCHARGING_V2H",
        "CHARGING_STATUS_V2_DISCHARGING_V2L",
        "CHARGING_STATUS_V2_SMART_CHARGING",
        "CHARGING_STATUS_V2_SMART_CHARGING_PAUSED",
        "CHARGING_STATUS_V2_SMART_CHARGING_WILL_NOT_FINISH",
        "CHARGING_STATUS_V2_ERROR",
        "CHARGING_STATUS_V2_DONE",
    ),
)

CHARGING_TYPE = EnumSpec(
    prefix="CHARGING_TYPE_",
    values=(
        "CHARGING_TYPE_UNSPECIFIED",
        "CHARGING_TYPE_NONE",
        "CHARGING_TYPE_AC",
        "CHARGING_TYPE_DC",
        "CHARGING_TYPE_WIRELESS",
    ),
)

ENGINE_COOLANT_LEVEL_WARNING = EnumSpec(
    prefix="ENGINE_COOLANT_LEVEL_WARNING_",
    values=(
        "ENGINE_COOLANT_LEVEL_WARNING_UNSPECIFIED",
        "ENGINE_COOLANT_LEVEL_WARNING_NO_WARNING",
        "ENGINE_COOLANT_LEVEL_WARNING_TOO_LOW",
    ),
)

ERROR_TYPE = EnumSpec(
    prefix="ERROR_TYPE_",
    values=(
        "ERROR_TYPE_UNSPECIFIED",
        "ERROR_TYPE_GENERIC_ERROR",
        "ERROR_TYPE_INTERRUPTED",
        "ERROR_TYPE_FUEL_LOW",
        "ERROR_TYPE_BATTERY_LOW",
        "ERROR_TYPE_NOT_CONNECTED_TO_POWER",
        "ERROR_TYPE_NO_START_NEEDED",
        "ERROR_TYPE_SERVICE_REQUIRED",
        "ERROR_TYPE_TEMPORARILY_NOT_AVAILABLE",
        "ERROR_TYPE_PERSISTENT_ERROR_DETECTED",
        "ERROR_TYPE_REACHED_MAX_RUNTIME",
    ),
)

EXTERIOR_LIGHT_WARNING = EnumSpec(
    prefix="EXTERIOR_LIGHT_WARNING_",
    values=(
        "EXTERIOR_LIGHT_WARNING_UNSPECIFIED",
        "EXTERIOR_LIGHT_WARNING_NO_WARNING",
        "EXTERIOR_LIGHT_WARNING_FAILURE",
    ),
)

HEATING_INTENSITY = EnumSpec(
    prefix="HEATING_INTENSITY_",
    values=(
        "HEATING_INTENSITY_UNSPECIFIED",
        "HEATING_INTENSITY_OFF",
        "HEATING_INTENSITY_LOW",
        "HEATING_INTENSITY_MEDIUM",
        "HEATING_INTENSITY_HIGH",
    ),
)

HEATING_LEVEL = EnumSpec(
    prefix="I_",
    values=(
        "I_UNDEFINED",
        "I_OFF",
        "I_LEVEL1",
        "I_LEVEL2",
        "I_LEVEL3",
    ),
)

LOCATION_TYPE = EnumSpec(
    prefix="LOCATION_TYPE_",
    values=(
        "LOCATION_TYPE_UNSPECIFIED",
        "LOCATION_TYPE_RECENT",
        "LOCATION_TYPE_SAVED",
        "LOCATION_TYPE_SAVED_3RD_PARTY",
    ),
)

LOCK_STATUS = EnumSpec(
    prefix="LOCK_STATUS_",
    values=(
        "LOCK_STATUS_UNSPECIFIED",
        "LOCK_STATUS_UNLOCKED",
        "LOCK_STATUS_LOCKED",
    ),
)

LOW_VOLTAGE_BATTERY_WARNING = EnumSpec(
    prefix="LOW_VOLTAGE_BATTERY_WARNING_",
    values=(
        "LOW_VOLTAGE_BATTERY_WARNING_UNSPECIFIED",
        "LOW_VOLTAGE_BATTERY_WARNING_NO_WARNING",
        "LOW_VOLTAGE_BATTERY_WARNING_TOO_LOW",
    ),
)

MAIN_CLIMATE_RUNNING_STATUS = EnumSpec(
    prefix="MAIN_CLIMATE_RUNNING_STATUS_",
    values=(
        "MAIN_CLIMATE_RUNNING_STATUS_UNSPECIFIED",
        "MAIN_CLIMATE_RUNNING_STATUS_ON",
        "MAIN_CLIMATE_RUNNING_STATUS_OFF",
    ),
)

MANUAL_PRECONDITIONING_STATUS = EnumSpec(
    prefix="MANUAL_PRECONDITIONING_STATUS_",
    values=(
        "MANUAL_PRECONDITIONING_STATUS_UNSPECIFIED",
        "MANUAL_PRECONDITIONING_STATUS_OFF",
        "MANUAL_PRECONDITIONING_STATUS_PRECONDITIONING_FINISHED",
        "MANUAL_PRECONDITIONING_STATUS_ON",
        "MANUAL_PRECONDITIONING_STATUS_BATTERY_TEMPERATURE_OPTIMAL",
        "MANUAL_PRECONDITIONING_STATUS_UNAVAILABLE",
    ),
)

MANUAL_PRECONDITIONING_UNAVAILABLE_REASON = EnumSpec(
    prefix="MANUAL_PRECONDITIONING_UNAVAILABLE_REASON_",
    values=(
        "MANUAL_PRECONDITIONING_UNAVAILABLE_REASON_UNSPECIFIED",
        "MANUAL_PRECONDITIONING_UNAVAILABLE_REASON_STATUS_FAULT",
        "MANUAL_PRECONDITIONING_UNAVAILABLE_REASON_CHARGING_IN_PROGRESS",
        "MANUAL_PRECONDITIONING_UNAVAILABLE_REASON_LOW_ENERGY",
        "MANUAL_PRECONDITIONING_UNAVAILABLE_REASON_PRECONDITIONING_PLANNED",
        "MANUAL_PRECONDITIONING_UNAVAILABLE_REASON_PRECONDITIONING_IN_PROGRESS",
    ),
)

OIL_LEVEL_WARNING = EnumSpec(
    prefix="OIL_LEVEL_WARNING_",
    values=(
        "OIL_LEVEL_WARNING_UNSPECIFIED",
        "OIL_LEVEL_WARNING_NO_WARNING",
        "OIL_LEVEL_WARNING_SERVICE_REQUIRED",
        "OIL_LEVEL_WARNING_TOO_LOW",
        "OIL_LEVEL_WARNING_TOO_HIGH",
    ),
)

OPEN_STATUS = EnumSpec(
    prefix="OPEN_STATUS_",
    values=(
        "OPEN_STATUS_UNSPECIFIED",
        "OPEN_STATUS_OPEN",
        "OPEN_STATUS_CLOSED",
        "OPEN_STATUS_AJAR",
    ),
)

RUNNING_STATUS = EnumSpec(
    prefix="RUNNING_STATUS_",
    values=(
        "RUNNING_STATUS_UNSPECIFIED",
        "RUNNING_STATUS_ON",
        "RUNNING_STATUS_OFF",
        "RUNNING_STATUS_PENDING",
    ),
)

SERVICE_WARNING = EnumSpec(
    prefix="SERVICE_WARNING_",
    values=(
        "SERVICE_WARNING_UNSPECIFIED",
        "SERVICE_WARNING_NO_WARNING",
        "SERVICE_WARNING_UNKNOWN_WARNING",
        "SERVICE_WARNING_REGULAR_MAINTENANCE_ALMOST_TIME_FOR_SERVICE",
        "SERVICE_WARNING_ENGINE_HOURS_ALMOST_TIME_FOR_SERVICE",
        "SERVICE_WARNING_DISTANCE_DRIVEN_ALMOST_TIME_FOR_SERVICE",
        "SERVICE_WARNING_REGULAR_MAINTENANCE_TIME_FOR_SERVICE",
        "SERVICE_WARNING_ENGINE_HOURS_TIME_FOR_SERVICE",
        "SERVICE_WARNING_DISTANCE_DRIVEN_TIME_FOR_SERVICE",
        "SERVICE_WARNING_REGULAR_MAINTENANCE_OVERDUE_FOR_SERVICE",
        "SERVICE_WARNING_ENGINE_HOURS_OVERDUE_FOR_SERVICE",
        "SERVICE_WARNING_DISTANCE_DRIVEN_OVERDUE_FOR_SERVICE",
    ),
)

START_REASON = EnumSpec(
    prefix="START_REASON_",
    values=(
        "START_REASON_UNSPECIFIED",
        "START_REASON_REMOTE",
        "START_REASON_MANUALLY_FROM_CAR",
        "START_REASON_TIMER",
        "START_REASON_KEEP_CLIMATE",
    ),
)

SYNC_STATUS = EnumSpec(
    prefix="",
    values=(
        "SYNC_STATUS_UNKNOWN",
        "SYNCING",
        "SYNCED",
        "RETRYING",
        "RETRYING_CAR_OFFLINE",
        "ERROR",
    ),
)

TYRE_PRESSURE_WARNING = EnumSpec(
    prefix="TYRE_PRESSURE_WARNING_",
    values=(
        "TYRE_PRESSURE_WARNING_UNSPECIFIED",
        "TYRE_PRESSURE_WARNING_NO_WARNING",
        "TYRE_PRESSURE_WARNING_VERY_LOW_PRESSURE",
        "TYRE_PRESSURE_WARNING_LOW_PRESSURE",
        "TYRE_PRESSURE_WARNING_HIGH_PRESSURE",
    ),
)

UNAVAILABLE_REASON = EnumSpec(
    prefix="UNAVAILABLE_REASON_",
    values=(
        "UNAVAILABLE_REASON_UNSPECIFIED",
        "UNAVAILABLE_REASON_NO_INTERNET",
        "UNAVAILABLE_REASON_POWER_SAVING_MODE",
        "UNAVAILABLE_REASON_CAR_IN_USE",
        "UNAVAILABLE_REASON_OTA_INSTALLATION_IN_PROGRESS",
        "UNAVAILABLE_REASON_STOLEN_VEHICLE_TRACKING_IN_PROGRESS",
        "UNAVAILABLE_REASON_SERVICE_MODE_ACTIVE",
    ),
)

USAGE_MODE = EnumSpec(
    prefix="USAGE_MODE_",
    values=(
        "USAGE_MODE_UNSPECIFIED",
        "USAGE_MODE_ABANDONED",
        "USAGE_MODE_INACTIVE",
        "USAGE_MODE_CONVENIENCE",
        "USAGE_MODE_ACTIVE",
        "USAGE_MODE_DRIVING",
        "USAGE_MODE_ENGINE_ON",
        "USAGE_MODE_ENGINE_OFF",
    ),
)

VENTILATION = EnumSpec(
    prefix="VENTILATION_",
    values=(
        "VENTILATION_UNSPECIFIED",
        "VENTILATION_COOLING",
        "VENTILATION_HEATING",
        "VENTILATION_NEUTRAL",
    ),
)

WARNING_TYPE = EnumSpec(
    prefix="WARNING_TYPE_",
    values=(
        "WARNING_TYPE_UNSPECIFIED",
        "WARNING_TYPE_BATTERY_LOW",
        "WARNING_TYPE_RUN_TIME_NEARING_LIMIT",
    ),
)

WASHER_FLUID_LEVEL_WARNING = EnumSpec(
    prefix="WASHER_FLUID_LEVEL_WARNING_",
    values=(
        "WASHER_FLUID_LEVEL_WARNING_UNSPECIFIED",
        "WASHER_FLUID_LEVEL_WARNING_NO_WARNING",
        "WASHER_FLUID_LEVEL_WARNING_TOO_LOW",
    ),
)

WEEKDAY = EnumSpec(
    prefix="",
    values=(
        "UNSPECIFIED",
        "MONDAY",
        "TUESDAY",
        "WEDNESDAY",
        "THURSDAY",
        "FRIDAY",
        "SATURDAY",
        "SUNDAY",
    ),
)
